name: ga-workflow
on:
  push:
    - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: install dependency
        run: yarn

      - name: build
        run: yarn build
